spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prosoccer?autoReconnect=true&useSSL=false
    username: root
    password: Pasw0rd!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update